version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    links:
      - db
    volumes:
     - .:/go
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ChallengeDB
    restart: always
    volumes:
      - ./data/data.sql:/docker-entrypoint-initdb.d/data.sql
    stdin_open: true
    tty: true