version: "3"

services:
  db:
    container_name: "ChallengeDB"
    image: "mysql:8"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    volumes:
      - ./data/data.sql:/docker-entrypoint-initdb.d/data.sql
    stdin_open: true
    tty: true